use_frameworks!

platform :ios, '9.0'

target 'HHNetworkHelper_Example' do
  pod 'HHNetworkHelper', :path => '../'

  target 'HHNetworkHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
